CREATE DATABASE IF NOT EXISTS testing_db;
USE testing_db;
CREATE TABLE IF NOT EXISTS test_table(

student_id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20),
age VARCHAR(10),
Department VARCHAR(10),
email VARCHAR(20),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);